#!/bin/bash
# migrate.sh - one-time migration of the existing "Applying AI at Work" repo
# to the canvas-course-builder structure.
#
# This script moves design docs to <course>/design/, archives the legacy iframe
# template, creates new directories for build outputs, and updates the decision
# log and open-questions files.
#
# Run once from the repo root after unzipping the builder scaffold on top of
# this repo. The script is idempotent: running it twice is safe.

set -euo pipefail

echo "=== Canvas Course Builder Migration ==="
echo ""

# Sanity checks
if [ ! -f "context/decision-log.md" ]; then
  echo "ERROR: context/decision-log.md not found. Is this the right repo?"
  echo "Expected to be run from the 'Applying AI at Work' repo root."
  exit 1
fi

if [ ! -f "prompts/ralph-prompt.md" ]; then
  echo "ERROR: prompts/ralph-prompt.md not found. Unzip the builder scaffold first."
  exit 1
fi

USE_GIT=0
if [ -d ".git" ]; then
  USE_GIT=1
  echo "Git repo detected. Using 'git mv' for file moves."
else
  echo "No git repo detected. Using plain 'mv' for file moves."
fi

mv_file() {
  local src="$1"
  local dst="$2"
  if [ ! -e "$src" ]; then
    echo "  skip (not found): $src"
    return
  fi
  if [ -e "$dst" ]; then
    echo "  skip (already exists): $dst"
    return
  fi
  mkdir -p "$(dirname "$dst")"
  if [ "$USE_GIT" -eq 1 ] && git ls-files --error-unmatch "$src" >/dev/null 2>&1; then
    git mv "$src" "$dst"
  else
    mv "$src" "$dst"
  fi
  echo "  moved: $src -> $dst"
}

echo ""
echo "--- Step 1: Move design docs into <course>/design/ ---"
for course in course1 course2; do
  if [ -d "$course" ]; then
    mv_file "$course/README.md"    "$course/design/README.md"
    mv_file "$course/structure.md" "$course/design/structure.md"
    mv_file "$course/outcomes.md"  "$course/design/outcomes.md"

    # Replace the empty modules/ placeholder with sprints/ + manifests/
    if [ -f "$course/modules/.gitkeep" ]; then
      rm "$course/modules/.gitkeep"
      rmdir "$course/modules" 2>/dev/null || true
      echo "  removed: $course/modules/ (replaced by sprints/ and manifests/)"
    fi
    mkdir -p "$course/sprints" "$course/manifests"
    touch "$course/sprints/.gitkeep" "$course/manifests/.gitkeep"
  fi
done

echo ""
echo "--- Step 2: Write new top-level README for each course ---"
for course in course1 course2; do
  if [ -d "$course/design" ] && [ ! -f "$course/README.md" ]; then
    course_num=${course#course}
    course_name="Problem Framing with AI"
    [ "$course_num" = "2" ] && course_name="Building Solutions with AI"
    cat > "$course/README.md" << EOF
# Course $course_num: $course_name

This directory has three parts:

- \`design/\` - authoritative course design (README, structure, outcomes)
- \`sprints/\` - built canvas artifacts (generated by the builder)
- \`manifests/\` - canvas instance state (generated by the builder)

See \`design/README.md\` for the course overview.
See the repo root \`README-BUILDER.md\` for builder usage.
EOF
    echo "  wrote: $course/README.md"
  fi
done

echo ""
echo "--- Step 3: Archive legacy iframe template ---"
mkdir -p archive/legacy-iframe-template
mv_file "shared/templates/sprint-template.html" "archive/legacy-iframe-template/sprint-template.html"
mv_file "shared/templates/README.md"            "archive/legacy-iframe-template/README.md"
rmdir shared/templates 2>/dev/null || true
rmdir shared 2>/dev/null || true

if [ ! -f "archive/legacy-iframe-template/WHY-ARCHIVED.md" ]; then
  cat > archive/legacy-iframe-template/WHY-ARCHIVED.md << 'EOF'
# Why This Is Archived

This template represents the legacy CTI pattern: a static HTML shell served from a separate site and embedded into canvas pages via iframes. That pattern was used in CST349 and CST395.

It is superseded in this repo by the canvas-course-builder pipeline: canvas-agnostic markdown in the repo, generated directly into canvas pages / assignments / discussions / quizzes via the Canvas REST API.

Kept here as reference for:

- Visual design intent (sticky counter, journey pills, collapsible sprint details)
- Team members asking "why don't we use iframes?"
- Historical context for the migration

Do not ship this pattern in new work. Student feedback consistently found the iframe-embedded pages cluttered, word-dense, and hard to navigate for finding action items.
EOF
  echo "  wrote: archive/legacy-iframe-template/WHY-ARCHIVED.md"
fi

echo ""
echo "--- Step 4: Prepend decision-log entry ---"
TODAY=$(date '+%Y-%m-%d')
DECISION_MARKER="Adopted canvas-course-builder"
if ! grep -q "$DECISION_MARKER" context/decision-log.md; then
  TMP=$(mktemp)
  # Keep the header (first heading line + blank line), inject new entry after it
  head -2 context/decision-log.md > "$TMP"
  cat >> "$TMP" << EOF

---

**$TODAY - Adopted canvas-course-builder; answered "delivery platform" open question**

Adopted the canvas-course-builder scaffold as the delivery pipeline: a Ralph-loop-driven system that generates canvas artifacts directly from canvas-agnostic markdown via the Canvas REST API. Canvas is now the delivery platform. Canvas-agnostic markdown in this repo is the source of truth; per-canvas-course manifests (one per course shell) map MD files to canvas IDs. The legacy iframe-embedding pattern used in CST349 and CST395 is archived to archive/legacy-iframe-template/ for reference. The corresponding entry in open-questions.md is now resolved.

EOF
  tail -n +3 context/decision-log.md >> "$TMP"
  mv "$TMP" context/decision-log.md
  echo "  prepended decision-log entry dated $TODAY"
else
  echo "  skip: decision-log entry already present"
fi

echo ""
echo "--- Step 5: Mark delivery-platform question resolved ---"
if grep -qF "What delivery platform will be used?" context/open-questions.md && \
   ! grep -qF "Canvas.** See \`context/decision-log.md\`" context/open-questions.md; then
  python3 - << 'PYEOF'
import pathlib
p = pathlib.Path("context/open-questions.md")
text = p.read_text()
old = "- What delivery platform will be used? Canvas, a custom platform, or something else?\n"
if old in text:
    text = text.replace(old, "")
if "## Resolved" not in text:
    text = text.rstrip() + "\n\n## Resolved\n\n"
resolved_line = "- What delivery platform will be used? **Canvas.** See `context/decision-log.md` for the adoption entry. The pipeline lives in `canvas_sync/`, `.claude/`, and `prompts/ralph-prompt.md`.\n"
if resolved_line not in text:
    text += resolved_line
p.write_text(text)
PYEOF
  echo "  updated: context/open-questions.md"
else
  echo "  skip: delivery-platform question already resolved or absent"
fi

echo ""
echo "--- Step 6: Merge .gitignore additions ---"
if [ -f .gitignore ]; then
  # Append builder-specific ignores if not already present
  for pattern in ".env" ".ralph/" "__pycache__/" ".claude/agent-memory-local/"; do
    if ! grep -qF "$pattern" .gitignore 2>/dev/null; then
      echo "$pattern" >> .gitignore
      echo "  added to .gitignore: $pattern"
    fi
  done
else
  echo "  no existing .gitignore; one was provided by the scaffold"
fi

echo ""
echo "--- Step 7: Make scripts executable ---"
chmod +x ralph.sh migrate.sh 2>/dev/null || true
echo "  chmod +x ralph.sh migrate.sh"

echo ""
echo "=== Migration complete ==="
echo ""
echo "Review the changes:"
echo "  git status"
echo "  git diff --stat"
echo ""
echo "Then commit:"
echo "  git add -A"
echo "  git commit -m 'feat: adopt canvas-course-builder, restructure for canvas-native delivery'"
echo ""
echo "Next: copy .env.example to .env and fill in canvas credentials + course IDs."
